version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Store Marvel Public Key
          command: echo "publicKey=$MARVEL_PUBLIC_KEY" >> ~/code/local.properties

      - run:
          name: Store Marvel Private Key
          command: echo "privateKey=$MARVEL_PRIVATE_KEY" >> ~/code/local.properties

      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x ./gradlew
            ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew test

      - store_artifacts:
          path: app/build/reports

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/reports

      - run:
          name: Run Code Coverage
          command: ./gradlew build jacocoTestReport

      - run:
          name: Submit Code Coverage results to codecov.io
          command: bash <(curl -s https://codecov.io/bash)